[project]
name = 'Tokenized-Industrial-Equipment-Performance-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-registration]
path = 'contracts/asset-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-alert]
path = 'contracts/maintenance-alert.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-benchmark]
path = 'contracts/performance-benchmark.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-data]
path = 'contracts/sensor-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
